name: simbaid
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=24.0
  - pip:
      - fastapi>=0.115
      - uvicorn[standard]>=0.30
      - pydantic>=2.7
      - pydantic-settings>=2.3
      - python-dotenv>=1.0
      - groq>=0.9
      - httpx>=0.27
      - pytest>=8.2
      - pytest-cov>=5.0
      - requests>=2.32
